### PR TITLE
Fix retries for POST requests

### LINKED ISSUE #42: when a POST operation returns >= 500 the retry fails
apparently it's because the request body is already read and not restored before retrying

here's a possible solution https://medium.com/@xoen/golang-read-from-an-io-readwriter-without-loosing-its-content-2c6911805361

and it's likely happening here:

https://github.com/gojektech/heimdall/blob/master/hystrix/hystrix_client.go#L152

### PR DESCRIPTION
**Pull request by dcu**
It replaces the request body with a bytes.Reader that's reset after
every attempt.

Fixes #42

### CODE REVIEW

File: httpclient/client.go [hunk 1]
```diff
@@ -120,25 +120,29 @@ func (c *Client) Delete(url string, headers http.Header) (*http.Response, error)
...
+		bodyReader = bytes.NewReader(reqData)
+		request.Body = ioutil.NopCloser(bodyReader) // prevents closing the body between retries
 	}
+
 	multiErr := &valkyrie.MultiError{}
 	var response *http.Response
 
 	for i := 0; i <= c.retryCount; i++ {
 		var err error
-		request.Body = ioutil.NopCloser(bytes.NewBuffer(reqBuffer))
```
Comment (rShetty) [inline httpclient/client.go]: @dcu Do we need Seek, wouldn't just setting `request.Body` work in the next retry ? The solution which was there before. Is this to prevent multiple allocations ?

Comment (dcu) [reply httpclient/client.go]: hi, yes it prevents multiple allocations and the behavior is the same. I added tests and benchmarks to test that

Comment (dcu) [reply httpclient/client.go]: do you have any concern?

Comment (rShetty) [reply httpclient/client.go]: @dcu No concerns as such, was curious on how does this add benefit. Cool not allocating everytime makes sense. Thanks

**Comment by rShetty** [comment]
@dcu Looks good to me. Thanks for this PR. Merging.
